### PR TITLE
Add include_origin parameter

### PR DESCRIPTION
**Pull request by mikker**
See README for description. A bit in doubt whether `with_origin` is the best parameter name. Is `include_origin` or something else entirely better?

### CODE REVIEW

**Comment by estolfo** [comment]
maybe `origin: true` ?

**Comment by mikker** [comment]
That wouldn't work if someone wanted to add to the `origin` fields manually 🤷‍♂️

**Comment by mikker** [comment]
I guess, it could if we just `case` on it being either `Hash` or `true`

**Comment by estolfo** [comment]
Is that a common use case-- to add the origin fields manually?

**Comment by mikker** [comment]
There are no use cases 😅 so it's up to us to judge on gut feelings.

**Comment by estolfo** [comment]
Up to you then🔮

**Comment by mikker** [comment]
Renamed to `include_origin` to align with the Java lib, https://www.elastic.co/guide/en/ecs-logging/java/current/setup.html#_use_the_ecs_encoderformatterlayout

**Pull request merged**
